# Generated by Django 6.0.4 on 2026-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='critical_missing',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='experience_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='keyword_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='matched_by_group',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='missing_by_group',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='score_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='section_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='semantic_scores',
            field=models.JSONField(default=dict),
        ),
    ]
