# Generated by Django 6.0.4 on 2026-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_matchresult_critical_missing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='ai_rewritten',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
